services:

    shapecode_twig_doctrine_loader.twig_loader.doctrine:
        class: Shapecode\Bundle\TwigDoctrineLoaderBundle\Twig\Loader\DoctrineLoader
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.loader, priority: 10 }
